AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  whattheversion

  try to get the latest version of the specified git repo, docker image or helm chart

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  HostedZoneId:
    Type: String
    Default: Z3CBRYU3UXXFKT
  DomainName:
    Type: String
    Default: whattheversion.hutter.cloud

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
     # would be really cool to use openapi spec to automatically
     # configure all routes
     # the problem is that the lambda invoke permission isnt created
     # and i havent found a way how to retrieve the route arn dynamically
     # from sam/cf to reference it as source arn in "AWS::Lambda::Permission"
     # DefinitionBody:
     #   'Fn::Transform':
     #     Name: 'AWS::Include'
     #     Parameters:
     #       Location: ./openapi-spec.yaml
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref Certificate
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Ref HostedZoneId

  GitLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: git
        Description: Contains git binary and libs
        ContentUri: ./layers/git
        RetentionPolicy: Retain

  FunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: whattheversionlayer
        Description: Dependencies for whattheversion
        ContentUri: ./layers/whattheversion
        CompatibleRuntimes:
          - python3.9
        RetentionPolicy: Retain

  GitVersion:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/git-api
      Handler: main.handler
      Runtime: python3.9
      Architectures: ['x86_64']
      Timeout: 300
      Layers:
        - !Ref FunctionLayer
        - !Ref GitLayer
      Environment:
        # thanks to: https://github.com/binxio/aws-lambda-git
        Variables:
          LD_LIBRARY_PATH: "/opt/git/lib:$LD_LIBRARY_PATH"
          PATH: "/opt/git/bin:$PATH"
      Events:
        WhatTheVersionEvent:
          Type: HttpApi 
          Properties:
            Path: /git
            Method: post
            ApiId: !Ref HttpApi
